[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "npym"
dynamic = ["version"]
description = 'A storage platform for build artefacts.'
readme = "README.md"
requires-python = ">=3.8"
license = "MIT"
keywords = []
authors = [
  { name = "Samuel Fry", email = "samueljfry@protonmail.com" },
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: Python :: Implementation :: PyPy",
]
dependencies = [
  "fastapi[standard]>=0.116.1",
  "sqlmodel>=0.0.24",
]

[project.urls]
Documentation = "https://github.com/U.N. Owen/npym#readme"
Issues = "https://github.com/U.N. Owen/npym/issues"
Source = "https://github.com/U.N. Owen/npym"

[tool.hatch.version]
path = "src/npym/__about__.py"

[tool.hatch.envs.default.scripts]
dev = "fastapi dev src/npym/main.py"

[tool.hatch.envs.types]
extra-dependencies = [
  "mypy>=1.0.0",
]

[tool.hatch.envs.types.scripts]
check = "mypy --install-types --non-interactive {args:src/npym tests}"

[tool.coverage.run]
source_pkgs = ["npym", "tests"]
branch = true
parallel = true
omit = [
  "src/npym/__about__.py",
]

[tool.coverage.paths]
npym = ["src/npym", "*/npym/src/npym"]
tests = ["tests", "*/npym/tests"]

[tool.coverage.report]
exclude_lines = [
  "no cov",
  "if __name__ == .__main__.:",
  "if TYPE_CHECKING:",
]

[tool.hatch.envs.hatch-test]
extra-dependencies = [
  "pytest-bdd",
]
